name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: npm install quasar
      - name: Run a multi-line script
        run: |
          npm run-script build,
          echo test, and deploy your project.
