name: Node CI
# 3f1fb5501c356e79c185d0f483468f9b06132a7d
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build, and test
        run: |
          yarn add quasar
          yarn run build --if-present
          git remote add origin https://HakonArnarS:${{ secrets.ACCESS_TOKEN }}@github.com/Hak
onArnarS/starbucks.git
          git subtree push --prefix dist origin gh-pages
          yarn test
        env:
          CI: true
